POST https://africananimalfacts.herokuapp.com/update/
Content-Type: application/json

{
    "animal":"Birds",
    "fact":"there are more birds in Kenya than anywhere else",
    "source":"Just Testing"
}


# postgres://animal_facts_user:XpmUz1tUfPmpzxgdlITNOpxTSMzZirK4@dpg-cmcens021fec73cpv7ng-a.oregon-postgres.render.com/animal_facts