# Generated by Django 4.0.5 on 2022-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=45)),
                ('fact', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=80)),
            ],
        ),
    ]
